#include <stdio.h>
#include <stdlib.h>

int main(){

    char mi_nombre[20];

    system("toilet --gay -f pagga 'NOMBRE' ");


    /* Bloque de entrada de datos */
    printf("Nombre: ");
    scanf(" %s", mi_nombre);

    printf("Seras mi princesa %s.\n", mi_nombre);

printf("^,^lxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK.....''....''.'',xXWMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,..''..................'',^lxKMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX............     ........'''lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO^...........         .  ....''.'.'WMMMMMMMMMMMWWWMMMMMMWMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l........... .          .  .........'WMMMMMMMMMWWWMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMK^......... .. . ..             ........oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMK...........       ...     ...  .......'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMo... .   ...       ..... ..  ..........^0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'...  ....               ............'dWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'    ....      ...       ...........^NMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.      ..        ............'...,0MMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl                    ........''^NMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK'.             .'..........'cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOl.     .. ....^^.....,cdx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0^'^d,...,,'..'^,',^lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkxXWMN.',,,',^,,,...'^cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNMMMMMo.,,,,,,''^....,^XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0XWWNWMMMMMK..c,,,,,'^'...,^NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMXl^,,,cdO00KWMMN.'',,,',^^..',^KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMO^'',,^^^^odxdxXN.oc,,,,,^.',,^OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMNd',^^^^odllccl.xX^,,',,.,,,oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdodOWMWo^^^^.c0X0d^^.',^kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,,' ,^dXMX0OOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,.',^dOoddloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW'lNMO,.....'lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM^cMK...''....'dWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,Md....''''^WMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0.00o....''''lMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.lWM^....''...''XMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMWWW\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'^MMK....'.'...'KMMMMMMMMMMMMMMMMMMMWMMMMMMMWWWWWWMMWWWW\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMc^MMMX^.....'.',XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWW\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo,MMMMMKd^...''dMMMMMMMMMMMMMMMMMMMMMMWMWMMMMWMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.WMMMMMMMWX0OkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0.NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMW\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX.XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX.KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0^0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNWMN.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMM'oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKWMMM^cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo^MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMM\n");


return EXIT_SUCCESS;
}
